### ISSUE TITLE
Post Minutes from Previous Meetings

### ISSUE THREAD

**Issue by pathawks** [AICSC/aicsc.github.io#5]
We need to post the minutes on the site.

If anybody *has* the minutes, let me know and we can work together to post them.

 - [x] February 6, 2015
 - [ ] February 20, 2015
 - [x] March 6, 2015

**Comment by ChadH1971** [comment]
I believe Brenda has all of those.

**Comment by pathawks** [comment]
I guess Feb 20 minutes are a lost cause&hellip; :confounded:

**Comment by ChadH1971** [comment]
Let me check my files. I might still have something.

**Comment by ChadH1971** [comment]
I don't know what happened with February Pat. I have an attendance roster
that Brenda sent to me, but I can't find anything for minutes.

**Comment by pathawks** [comment]
Welp, that's that, I guess.

**Comment by ChadH1971** [comment]
Part of why I felt I should step aside. I'll talk with you more when I see
you on Wednesday.
