### ISSUE TITLE
Removing Conference Call info from Footer of Agendas

### ISSUE THREAD

**Issue by asterwolf** [AICSC/aicsc.github.io#70]
Currently the following text gets displayed in the footer of all the agendas:

Notes:

Listen in on the Conference Call: 1-(712) 770-4700 Participant passcode: 991468

In accordance with the Ralph M. Brown Act, agendas are posted 72 hours before the meeting commences.

Agendas are posted electronically at aicsc.github.io

If you would like a copy of any of the agenda items listed, please email bccompsciclub@gmail.com

We no longer have Conference Calls available and so we should remove it from the footer of the agendas.

**Comment by pathawks** [comment]
[Here](https://github.com/AICSC/aicsc.github.io/blob/89645e27d36727528dd5b0f3a081555ff1582d4c/_layouts/agenda.html#L13-L20) is where that should be changed :+1:

**Comment by asterwolf** [comment]
Thanks Pat! I left this as a mental note for myself to remember to do so after class. :smile:
